### ISSUE TITLE
How do you obtain the 3D output of your desired image in Panehead?

### ISSUE THREAD

**Issue by MustafaHilmiYAVUZHAN** [SlimeVRX/SlimeVRX#56]

**Comment by SlimeVRX** [comment]
Please see [here](https://twitter.com/_hackmans_/status/1672715811566305280)

![image](https://github.com/SlimeVRX/SlimeVRX/assets/99313947/06827196-6d81-4eb9-ae75-eec262eeb45b)

**Comment by MustafaHilmiYAVUZHAN** [comment]
why I am here
