### ISSUE TITLE
Hello.SlimeVRX,I'm very confused to reproduce PIP

### ISSUE THREAD

**Issue by yuhuison** [SlimeVRX/SlimeVRX#57]
Hello，SlimeVRX , I am interesting in mocap project of VR such like SlimeVR.I found so are you very active in it.

I haved diy some piece imu using the chip bno085. But when I want to use it to reproduce PIP, I found the result is not very good.

Can u help me? I think we can share ideas and fruits and I can post some imus to you for testing.We can use Wechat to communicate.

**Comment by SlimeVRX** [comment]
Please add me!

**Comment by SlimeVRX** [comment]
I realy need BNO085 sensors for testing

**Comment by yuhuison** [comment]
Hi SlimeVRX, I have send  a friend request to you.

**Comment by SlimeVRX** [comment]
Hi @yuhuison, I lost my old Wechat account, can you help me authenticate it? Please send number 766253 to my account

**Comment by SlimeVRX** [comment]
I'm Tin, I'm from Vietnam, I'm asking for your sponsorship of the BNO085 sensor to continue doing my research

**Comment by SlimeVRX** [comment]
Sorry for the inconvenience!

**Comment by yuhuison** [comment]
i have send it !

**Comment by SlimeVRX** [comment]
Many Thanks!

**Comment by SlimeVRX** [comment]
Hi @yuhuison,

I failed to get my old Wechat account back.

Are you planning to continue supporting the BNO085 sensor for my team, we are short of sensors for testing. We really need your group's sponsorship.

Many Thanks!

Tin Nguyen

**Comment by SlimeVRX** [comment]
Hi @yuhuison,

We have the same goal, we promise to support you as much as possible!

**Comment by yuhuison** [comment]
oh,sorry , I am now so busy for my school because new terms begin，In fact ， our hardware is not stable and we are fixing some problems , so it is not can be use now, but I'am glad to share the progress of it, and I promise that I will fulfill it to help yours. how can i contact of you ？ do u have another wechat account or any other IM app?

**Comment by yuhuison** [comment]
@SlimeVRX

**Comment by SlimeVRX** [comment]
Hi @yuhuison 

Sorry, My current job is also very busy, when I have free time I will work on mocap.
My Wechat is broken, I can't get back my old account with my phone number. 
Do you use Facebook, Skype, Slack, Twitter or Discord?

- Facebook: FB.com/thanhtin1997
- Skype: thanhtin1997_1
- Slack: slimevrx@gmail.com
- Twitter: @Tn23008624
- Discord: thanhtin1997#2352

**Comment by SlimeVRX** [comment]
Hi @yuhuison

I see you mentioned that the hardware is having problems, I can help you with hardware programming. I think I can assist you a lot but I also don't have much time. So if possible, let's make a plan together and execute it.

**Comment by SlimeVRX** [comment]
Hi @yuhuison. Please check help me!

**Comment by SlimeVRX** [comment]
Hi @yuhuison. I need sensors for experiments, Can you sell me 6 BNO085 sensors?

**Comment by SlimeVRX** [comment]
Hi @yuhuison. I really sensor for testing, Please sell me 6 BNO085 sensors?

**Comment by SlimeVRX** [comment]
Hi @yuhuison. 

I really sensor for testing. Our sensors are currently inaccurate. 
Please sell me 6 BNO085 sensors?

Thank you very much!

Best wishes

Tin Nguyen Thanh
